[theme]
primaryColor = "#00A5AC"
base = "light"
borderColor = "#E3E8EC"
baseRadius = "10px"
secondaryBackgroundColor = "#EEF2F5"

[server]
headless = true
enableXsrfProtection = true

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
